[package]
name = "interpreter"
version = "0.1.0"
authors = ["ec2-user"]
edition = "2018"
build = "build.rs"

[dependencies]
clap = "2.33.0"
libc = "0.2"
gcc = "0.3"

[build-dependencies]
bindgen = "0.50"
gcc = "0.3"
